Repository sprint-military-9team/sprint_4_thejulge, pull requests merged in 2024-04, with the labels that each got.

#10 Feat#4 card 및 버튼 구현
  .eslintrc.json
  src/components/common/Button/Button.tsx
  src/components/common/Button/button.module.scss
  src/components/common/Button/index.ts
  src/components/common/Card/Card.tsx
  src/components/common/Card/card.module.scss
  src/components/common/Card/index.ts
  src/styles/_color.scss
  src/styles/_common.scss
  src/styles/_reset.scss
Labels: 공통 컴포넌트

#16 Feat#11 filter컴포넌트
  .eslintrc.json
  src/components/common/Button/Button.tsx
  src/components/common/Button/button.module.scss
  src/components/listPage/Filter/Filter.tsx
  src/components/listPage/Filter/filter.module.scss
  src/components/listPage/Filter/index.ts
  src/constants/SEOUL.ts
  src/styles/_color.scss
  src/styles/_reset.scss
Labels: 공통 컴포넌트

#26 Feat#23 footer
  src/app/page.tsx
  src/components/common/Footer/Footer.module.scss
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/types.ts
  src/styles/_index.scss
  src/styles/_reset.scss
Labels: 공통 컴포넌트

#15 Feat#3 header
  public/assets/close_icon.svg
  public/assets/header_logo.svg
  public/assets/search_icon.svg
  src/app/page.module.css
  src/app/utils/constants.ts
  src/app/utils/getNotificationContent.ts
  src/app/utils/getTimeDifference.ts
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/components/common/Header/Notification.module.scss
  src/components/common/Header/notification.tsx
  src/components/common/Header/types.ts
  yarn.lock
Labels: 공통 컴포넌트

#39 Fix: header 컴포넌트 알림창 오류 수정
  src/components/common/Header/Header.tsx
  src/components/common/Header/Notification.module.scss
  src/components/common/Header/index.ts
  src/components/common/Header/notification.tsx
  src/styles/_mixins.scss
Labels: 오류

#48 Chore#47 input
  src/app/page.tsx
  src/components/common/Input/Input.module.scss
  src/components/common/Input/Input.tsx
Labels: 공통 컴포넌트, 리펙토링

#72 Refactor - 공고 상세 페이지 공고 등록 리스트 컴포넌트 서버 컴포넌트화
  src/apis/application.ts
  src/app/ownerNoticeDetail/page.tsx
  src/components/common/Pagination/Pagination.module.scss
  src/components/common/Pagination/Pagination.tsx
  src/components/common/Pagination/index.ts
  src/components/common/PaginationSSR/PaginationSSR.module.scss
  src/components/common/PaginationSSR/PaginationSSR.tsx
  src/components/common/Table/Table.module.scss
  src/components/common/Table/Table.tsx
  src/components/common/Table/TableButton.tsx
  src/components/common/Table/Tablebutton.module.scss
  src/components/ownerAddNotice/OwnerAddNotice.tsx
  src/components/ownerNoticeDetail/ApplicationList/ApplicationList.tsx
  src/components/profile/ProfileTableContainer.tsx
  src/middleware.ts
Labels: 리펙토링
